import ThemeRegistry from '@/components/themeRegistry/ThemeRegistry';
import AppBar from '@/components/AppBar';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ThemeRegistry>
					<AppBar />
					{children}
				</ThemeRegistry>
			</body>
		</html>
	);
}
